apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasourcing-ui  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasourcing-ui
  template:
    metadata:
      labels:
        app: datasourcing-ui
    spec:
      containers:
      - name: datasourcing-ui
<<<<<<< HEAD
        image: sandycis476/dataquaddev:latest
=======
        image: sandycis476/dataquadprod:latest
>>>>>>> 750e321351f94c927bb54218d456f17724614b5c
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: datasourcing-ui 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: datasourcing-ui
