export  const allSkills = [
  // Original skills
  "Java Full Stack Developer",
  "Python Full Stack Developer",
  "Java Developer",
  "Senior Java Developer",
  "Junior Java Developer",
  "Core Java Developer",
  "Spring Boot Developer",
  "Backend Java Developer",
  "Full Stack Java Developer",
  "J2EE Developer",
  "Microservices Java Developer",
  "Python Developer",
  "Senior Python Developer",
  "Junior Python Developer",
  "Python Backend Developer",
  "Python Full Stack Engineer",
  "Django Developer",
  "Flask Developer",
  "FastAPI Developer",
  "Python Automation Engineer",
  "React Developer",
  "React JS Developer",
  "Frontend Developer",
  "Senior Frontend Developer",
  "Junior Frontend Developer",
  "Angular Developer",
  "Angular JS Developer",
  "Vue JS Developer",
  "UI Developer",
  "Web Developer",
  "MERN Stack Developer",
  "MEAN Stack Developer",
  "Node JS Developer",
  "Express JS Developer",
  "JavaScript Developer",
  "TypeScript Developer",
  "Full Stack Web Developer",
  "Web Application Developer",
  "Software Developer",
  "Software Engineer",
  "Dot Net Developer",
  "C# Developer",
  "ASP.NET Developer",
  "Dot Net Full Stack Developer",
  ".NET Core Developer",
  "PHP Developer",
  "Laravel Developer",
  "CodeIgniter Developer",
  "WordPress Developer",
  "Drupal Developer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "Flutter Developer",
  "React Native Developer",
  "Kotlin Developer",
  "Swift Developer",
  "Xamarin Developer",
  "Cross Platform Developer",
  "Mobile Software Engineer",
  "DevOps Engineer",
  "AWS Developer",
  "Azure Developer",
  "GCP Developer",
  "Cloud Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Kubernetes Engineer",
  "Docker Engineer",
  "Infrastructure Engineer",
  "Data Engineer",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Python Data Engineer",
  "BI Developer",
  "Power BI Developer",
  "Tableau Developer",
  "Big Data Engineer",
  "QA Engineer",
  "Manual Tester",
  "Automation Tester",
  "Selenium Tester",
  "API Tester",
  "Performance Tester",
  "Test Engineer",
  "QA Automation Engineer",
  "ETL Tester",
  "Security Tester",
  "Database Developer",
  "SQL Developer",
  "PL/SQL Developer",
  "Oracle Developer",
  "MySQL Developer",
  "PostgreSQL Developer",
  "MongoDB Developer",
  "DBA Engineer",
  "Database Administrator",
  "NoSQL Developer",

  // From moreSkills
  "SAP ABAP Developer",
  "SAP FICO Consultant",
  "SAP SD Consultant",
  "SAP MM Consultant",
  "SAP HANA Developer",
  "Salesforce Developer",
  "Salesforce Admin",
  "ServiceNow Developer",
  "Oracle ERP Developer",
  "CRM Developer",
  "ERP Developer",
  "Workday Consultant",
  "Business Analyst",
  "Technical Analyst",
  "Product Analyst",
  "Product Manager",
  "Scrum Master",
  "Project Manager",
  "Program Manager",
  "Agile Coach",
  "Delivery Manager",
  "UI UX Designer",
  "Graphic Designer",
  "Web Designer",
  "Product Designer",
  "Figma Designer",
  "Adobe XD Designer",
  "Visual Designer",
  "Motion Designer",
  "Creative Designer",
  "Linux Administrator",
  "Windows Administrator",
  "System Administrator",
  "Network Engineer",
  "Server Engineer",
  "VMware Engineer",
  "Citrix Engineer",
  "Storage Engineer",
  "Virtualization Engineer",
  "Telecom Engineer",
  "Cyber Security Analyst",
  "Security Engineer",
  "SOC Analyst",
  "Ethical Hacker",
  "Penetration Tester",
  "IAM Engineer",
  "Risk Analyst",
  "Compliance Engineer",
  "InfoSec Engineer",
  "Network Security Engineer",
  "Blockchain Developer",
  "Web3 Developer",
  "Solidity Developer",
  "Smart Contract Developer",
  "Crypto Engineer",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "AR VR Developer",
  "Metaverse Developer",
  "Embedded Engineer",
  "IoT Developer",
  "Firmware Engineer",
  "Robotics Engineer",
  "Hardware Engineer",
  "Electronics Engineer",
  "VLSI Engineer",
  "PCB Design Engineer",
  "Automotive Software Engineer",
  "Control Systems Engineer",
  "Technical Support Engineer",
  "Application Support Engineer",
  "Production Support Engineer",
  "L1 Support Engineer",
  "L2 Support Engineer",
  "L3 Support Engineer",
  "Desktop Support Engineer",
  "Help Desk Engineer",
  "IT Support Analyst",
  "Research Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "Deep Learning Engineer",
  "Prompt Engineer",
  "Chatbot Developer",
  "Generative AI Engineer",
  "LLM Engineer",
  "AI Product Engineer",
  "Automation Developer",
  "Lead Developer",
  "Principal Engineer",
  "Software Architect",
  "Solution Architect",
  "Enterprise Architect",
  "Freelance Developer",
  "Remote Software Engineer",
  "Contract Developer",
  "Startup Engineer",

  // Missed / additional common skills
  "Ruby on Rails Developer",
  "Go Lang Developer",
  "Rust Developer",
  "Scala Developer",
  "Groovy Developer",
  "Perl Developer",
  "Haskell Developer",
  "Clojure Developer",
  "Elixir Developer",
  "SwiftUI Developer",
  "Objective-C Developer",
  "PowerShell Developer",
  "Bash Developer",
  "XML Developer",
  "JSON Developer",
  "RPA Developer",
  "UiPath Developer",
  "Blue Prism Developer",
  "Automation Anywhere Developer",
  "Salesforce Marketing Cloud Developer",
  "Microsoft Dynamics Developer",
  "ServiceNow Admin",
  "ITSM Engineer",
  "Jira Administrator",
  "Confluence Administrator",
  "GitHub Actions Engineer",
  "Jenkins Engineer",
  "GitLab CI Engineer",
  "CircleCI Engineer",
  "Ansible Engineer",
  "Chef Engineer",
  "Puppet Engineer",
  "Terraform Engineer",
  "Prometheus Engineer",
  "Grafana Engineer",
  "Elastic Stack Engineer",
  "Splunk Engineer",
  "Datadog Engineer",
  "New Relic Engineer",
  "APM Engineer",
  "Redis Developer",
  "RabbitMQ Developer",
  "Kafka Engineer",
  "Cassandra Developer",
  "Couchbase Developer",
  "DynamoDB Developer",
  "Firebase Developer",
  "Supabase Developer",
  "GraphQL Developer"
];